# data science

In [27]:
!pip list

Package                   Version
------------------------- --------------
altair                    5.5.0
anyio                     4.10.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.3.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.3.0
babel                     2.17.0
beautifulsoup4            4.13.4
bleach                    6.2.0
blinker                   1.9.0
cachetools                6.2.0
certifi                   2025.8.3
cffi                      1.17.1
charset-normalizer        3.4.3
click                     8.2.1
colorama                  0.4.6
comm                      0.2.3
contourpy                 1.3.3
cycler                    0.12.1
debugpy                   1.8.16
decorator                 5.2.1
defusedxml                0.7.1
et_xmlfile                2.0.0
executing                 2.2.0
fastjsonschema            2.21.2
fonttools                 4.59.1
fqdn           

In [2]:
# ndarray: 다차원 배열 생성
import numpy as np

In [29]:
arr = np.array([2025, 9, 5, 11, 21])
today_arr = [2025, 9, 5, 11, 21]
arr = np.array((1,2,3,4,5))
print(arr, type(arr), today_arr)

[1 2 3 4 5] <class 'numpy.ndarray'> [2025, 9, 5, 11, 21]


In [30]:
arr = np.array([1, 2, 3])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(3,)
1
3
int64


In [31]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6]])
print(arr_2d, type(arr_2d))
print(arr_2d.shape)
print(arr_2d.ndim)
print(arr_2d.size)
print(arr_2d.dtype)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
(2, 3)
2
6
int64


In [32]:
arr_int = np.array([2025,9,5])
print(arr_int.dtype)

arr_float = np.array([2025.1,9.1,5.1])
print(arr_float.dtype)

arr_vool = np.array([True, False, True])
print(arr_vool.dtype)

arr_str = np.array(['나','는','너야'])
print(arr_str.dtype)

int64
float64
bool
<U2


In [33]:
arr = np.array([2025.1,9.1,5.9])
print(arr.astype(int))

print(arr, arr.dtype)

[2025    9    5]
[2025.1    9.1    5.9] float64


In [34]:
arr = np.zeros([2, 3])
print(arr, arr.dtype)

arr_one = np.ones([2, 3])
print(arr_one, arr_one.dtype)

arr_full = np.full((2, 3), "나")
print(arr_full, arr_full.dtype)

[[0. 0. 0.]
 [0. 0. 0.]] float64
[[1. 1. 1.]
 [1. 1. 1.]] float64
[['나' '나' '나']
 ['나' '나' '나']] <U1


In [35]:
arr = np.array([[10, 20, 4], [30, 40, 1]])
print(arr.shape)

print(np.zeros_like(arr))
print(np.ones_like(arr))
print(np.full_like(arr, 9))

(2, 3)
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[9 9 9]
 [9 9 9]]


In [36]:
print(np.arange(0, 20, 5))

[ 0  5 10 15]


In [37]:
print(np.linspace(0, 0.5))

[0.         0.01020408 0.02040816 0.03061224 0.04081633 0.05102041
 0.06122449 0.07142857 0.08163265 0.09183673 0.10204082 0.1122449
 0.12244898 0.13265306 0.14285714 0.15306122 0.16326531 0.17346939
 0.18367347 0.19387755 0.20408163 0.21428571 0.2244898  0.23469388
 0.24489796 0.25510204 0.26530612 0.2755102  0.28571429 0.29591837
 0.30612245 0.31632653 0.32653061 0.33673469 0.34693878 0.35714286
 0.36734694 0.37755102 0.3877551  0.39795918 0.40816327 0.41836735
 0.42857143 0.43877551 0.44897959 0.45918367 0.46938776 0.47959184
 0.48979592 0.5       ]


In [38]:
print(np.logspace(1, 3, 5, .2))

[  10.           31.6227766   100.          316.22776602 1000.        ]


---

In [58]:
# indexing and slicing
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2d)
print(arr_2d.shape)
print(arr_2d[0][2], arr_2d[0, 2], arr_2d[(0, 2)])



[[1 2 3]
 [4 5 6]]
(2, 3)
3 3 3


In [63]:
arr = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])

print(arr[1, 0])  #44
print(arr[2, 1])  #88
print(arr[-1, -2])  #88 (음수 인덱스 활용)

44
88
88


In [73]:
arr = np.arange(1, 11)

print(arr[2:7])          #[3 4 5 6 7]
print(arr[::2])          #[1 3 5 7 9]
print(arr[4::])          #[5, 6, 7, 8, 9, 10]
print(arr[:7:])          #[1, 2, 3, 4, 5, 6, 7]
print(arr[::-1])         #[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


[3 4 5 6 7]
[1 3 5 7 9]
[ 5  6  7  8  9 10]
[1 2 3 4 5 6 7]
[10  9  8  7  6  5  4  3  2  1]


# 2차원 배열 슬라이싱

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr[0:2])
print(arr[:, 1:3])
print(arr[:-1, 0:1])
print(arr[:-1, :1])

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]
[[1]
 [4]]
[[1]
 [4]]


In [25]:
arr = np.arange(5, 31, 5)
print(arr[[1, 3, 5]])

[10 20 30]


In [26]:
arr = np.array([[5, 10, 15, 20], [25, 30, 35, 40],[45, 50, 55, 60]])

print(arr[[0, 1], [1, 2]])
print(arr.shape)
print(arr[[1, 2], [0, 2]])

[10 35]
(3, 4)
[25 55]


In [27]:
# 불리언 인덱싱

arr=np.arange(1, 6)
bools = [True, False, False, False, True]
print(arr[bools])
print(arr[arr>3])


[1 5]
[4 5]


In [28]:
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr[arr>4])

[5 6 7 8 9]


--------------

In [31]:
arr = np.array([10, 20, 30, 40, 50])

print(np.all(arr<0))
print(np.any(arr<0))

False
False
