In [1]:
import numpy as np

In [18]:
arr = np.random.randint(1, 11, 10)
print(arr)

print(np.sort(arr))

[ 6  9  4 10  7  1  2 10  9  9]
[ 1  2  4  6  7  9  9  9 10 10]


In [28]:
arr = np.random.randint(1, 10, (3, 4))
print(np.sort(arr))

[[1 2 6 8]
 [3 5 8 9]
 [4 4 5 8]]


In [32]:
print(np.sort(arr, axis=0))
print(np.sort(arr, axis=1))
print(np.sort(arr, axis=None))

[[2 5 3 1]
 [5 6 4 4]
 [8 8 8 9]]
[[1 2 6 8]
 [3 5 8 9]
 [4 4 5 8]]
[1 2 3 4 4 5 5 6 8 8 8 9]


In [33]:
arr = np.array([100, 400, 200, 300])
print(np.argsort(arr))
print(np.sort(arr))

[0 2 3 1]
[100 200 300 400]


In [38]:
names = np.array(['리사', '로제', '제니', '지수'])
album_sales = np.array([900, 870, 1000, 670])

ind = np.argsort(album_sales)[::-1]

print(names[ind])

['제니' '리사' '로제' '지수']


In [42]:
arr = np.array([[2025, 9, 8], [17, 30, 40]])
print(np.argsort(arr, axis=0))
print(np.argsort(arr))

[[1 0 0]
 [0 1 1]]
[[2 1 0]
 [0 1 2]]
