In [1]:
# ndarray 병합 및 분할
import numpy as np

In [2]:
arr = np.array([10, 20, 30])
arr1 = np.append(arr, 40)
arr2 = np.insert(arr, 1, 15)

print(arr, arr1, arr2)
print(arr2 is arr, arr2)

[10 20 30] [10 20 30 40] [10 15 20 30]
False [10 15 20 30]


In [33]:
# append
arr = np.arange(1, 13).reshape(3, 4)
print(np.append(arr, 40))
print(np.append(arr, [[5], [6], [7]], axis=1))

# insert
print(np.insert(arr, (2, 3), 100))
print(np.insert(arr, 1, [[10,20,30]], axis = 1))
print(np.insert(arr, 1, 100, axis = 1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 40]
[[ 1  2  3  4  5]
 [ 5  6  7  8  6]
 [ 9 10 11 12  7]]
[  1   2 100   3 100   4   5   6   7   8   9  10  11  12]
[[ 1 10  2  3  4]
 [ 5 20  6  7  8]
 [ 9 30 10 11 12]]
[[  1 100   2   3   4]
 [  5 100   6   7   8]
 [  9 100  10  11  12]]


In [43]:
#np.delete()

arr = np.arange(1, 13).reshape(3, 4)
print(arr)

print(np.delete(arr, 1))
print(np.delete(arr, 1, axis = 0))
print(np.delete(arr, 1, axis = 1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]


In [45]:
# ndarray 병합
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)

print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [49]:
print(np.append(arr1, arr2))
print(np.append(arr1, arr2, axis=0))
print(np.append(arr1, arr2[:, :2], axis = 1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4 13 14]
 [ 5  6  7  8 17 18]
 [ 9 10 11 12 21 22]]


In [53]:
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [56]:
print(np.concatenate((arr1, arr2)))
print(np.concatenate((arr1, arr2), axis = 1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [ ]:
# ndarray 분할
arr=np.concatenate((arr1, arr2))

In [67]:
print(np.split(arr, 2))
print(np.split(arr, 4, axis = 1))

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
[array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]]), array([[ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24]])]


In [68]:
n = 2
print(np.split(arr, n, axis = 0))
print(np.split(arr, n, axis = 1))

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]
