In [1]:
# ndarray 형태 변경
import numpy as np

In [16]:
# reshape
arr = np.arange(12).reshape(2, 2, 3)
print(arr)
print(arr.ndim)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
3


In [13]:
arr = arr.reshape(-1)
print(arr, arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


In [22]:
arr = arr.reshape(4, -1)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# np.ravel()

arr = np.arange(50).reshape(5, 10)
print(arr)

print(np.ravel(arr))

#np.expand.dims()
#np.squeeze()

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [28]:
arr_1d = np.arange(10)
print(arr_1d.shape, arr_1d)
print(np.expand_dims(arr_1d, axis=0))
print(np.expand_dims(arr_1d, axis=1))

(10,) [0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [29]:
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d.shape, arr_2d)
print(np.expand_dims(arr_2d, axis=0))
print(np.expand_dims(arr_2d, axis=1))

(2, 2) [[1 2]
 [3 4]]
[[[1 2]
  [3 4]]]
[[[1 2]]

 [[3 4]]]


In [39]:
arr=np.array([[1], [2]])
print(arr, arr.shape)

arr1 = np.squeeze(arr, axis=1)
print(arr1, arr1.shape)

[[1]
 [2]] (2, 1)
[1 2] (2,)
