In [2]:
import numpy as np

## ndarray 연산

In [13]:
arr_a = np.arange(1, 11).reshape(5, 2)
arr_b = np.full_like(arr_a, 3)
print(arr_a)
print(arr_b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [18]:
print(np.add(arr_a, arr_b))
print(np.subtract(arr_a, arr_b))
print(arr_a * arr_b)
print(arr_a / arr_b)

[[ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
[[-2 -1]
 [ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]]
[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]
[[0.33333333 0.66666667]
 [1.         1.33333333]
 [1.66666667 2.        ]
 [2.33333333 2.66666667]
 [3.         3.33333333]]


In [19]:
print(arr_a ** arr_b)
print(arr_a // arr_b)
print(arr_a % arr_b)

[[   1    8]
 [  27   64]
 [ 125  216]
 [ 343  512]
 [ 729 1000]]
[[0 0]
 [1 1]
 [1 2]
 [2 2]
 [3 3]]
[[1 2]
 [0 1]
 [2 0]
 [1 2]
 [0 1]]


In [20]:
print(np.sqrt(arr_a))

[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]
 [2.64575131 2.82842712]
 [3.         3.16227766]]


In [ ]:
# 브로드캐스팅 연산

arr_a = np.arange(1, 10).reshape(3, 3)

print(arr_a * np.full((3, 3), 5))
print(arr_a * np.array([5, 5, 5]))
print(arr_a * np.array([5]))
print(arr_a * 5)

print(np.arange(5, 46, 5).reshape(3, 3))

In [36]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([5, 10, 15])

print(arr1+arr2)

[[ 6 12 18]
 [ 9 15 21]]


In [ ]:
arr1 = np.array([[1, 2, 3, 4], [4, 5, 6, 7]]) #(2, 4)
arr2 = np.array([[100], [200]]) #(2, 1)
print(arr1+arr2)

[[101 102 103 104]
 [204 205 206 207]]


In [58]:
# 행렬 곱셈 (점곱연산 Dot Product / 내적)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1 * arr2)
print(np.dot(arr1, arr2))

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [60]:
arr2d = np.array([[1, 2], [3, 4]])
arr1d = np.array([[5], [6]])
print(np.dot(arr2d, arr1d))
# [1*5 + 2*6, 3*5 + 4*6]
# [17, 39]

[[17]
 [39]]


In [65]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])         #(2, 3)
arr4 = np.array([[7, 8], [9, 10], [11, 12]])    #(3, 2)

print(np.dot(arr3, arr4))
print(np.dot(arr4, arr3))
print(arr3@arr4)

[[ 58  64]
 [139 154]]
[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]
[[ 58  64]
 [139 154]]


In [66]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr@arr.T)

[[14 32]
 [32 77]]


In [69]:
print(np.matmul(arr3, arr4))

[[ 58  64]
 [139 154]]


In [83]:
# 연산 함수 및 집계 함수

arr_negative = np.array([[-1, -2], [-100, -200]])
arr_float = np.array([[1.234, -5.678], [-7.89, 10.123]])
arr = np.arange(1, 7).reshape(2, 3)

print(arr_negative, arr_float, arr)

[[  -1   -2]
 [-100 -200]] [[ 1.234 -5.678]
 [-7.89  10.123]] [[1 2 3]
 [4 5 6]]


In [85]:
print(np.abs(arr_negative))
print(np.round(arr_float))
print(np.round(arr_float, -1))
print(np.floor(arr_float))
print(np.trunc(arr_float))

[[  1   2]
 [100 200]]
[[ 1. -6.]
 [-8. 10.]]
[[  0. -10.]
 [-10.  10.]]
[[ 1. -6.]
 [-8. 10.]]
[[ 1. -5.]
 [-7. 10.]]


In [92]:

print(np.max(arr))
print(np.min(arr))

print(np.max(arr, axis=0)) # 행 고정, 같은 열에서 가장 큰 값
print(np.max(arr, axis=1))
print(np.min(arr, axis=0))
print(np.min(arr, axis=1))

6
1
[4 5 6]
[3 6]
[1 2 3]
[1 4]


In [95]:
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[5 7 9]
[ 6 15]


In [97]:
print(np.mean(arr, axis=0))

[2.5 3.5 4.5]
