# [실습] 붓꽃 다중분류

붓꽃은 세포핵을 둘러싼 꽃받침(sepal)과 꽃잎(petal)으로 구성되어 있으며, 이러한 특징을 기반으로 붓꽃의 품종을 식별할 수 있습니다.

- Setosa (세토사): Setosa는 붓꽃 중에서 가장 작은 꽃잎과 꽃받침을 가지고 있습니다.
꽃잎과 꽃받침이 비교적 짧고 뾰족한 모습을 갖고 있으며, 주로 흰색 또는 연한 분홍색을 띠고 있습니다.

- Versicolor (버시컬러): Versicolor는 Setosa보다 크고 긴 꽃잎과 꽃받침을 가지고 있습니다.
꽃잎의 색은 보통 연한 보라색이며, 중간 크기의 붓꽃입니다.

- Virginica (버지니카): Virginica는 붓꽃 중에서 가장 크고 긴 꽃잎과 꽃받침을 가지고 있습니다.
꽃잎의 색은 주로 짙은 보라색이며, 다른 품종들에 비해 상대적으로 더 큰 크기를 갖고 있습니다.

![](https://d.pr/i/4egoon+)

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib

font_path = 'C:/Windows/Fonts/gulim.ttc'
font = fm.FontProperties(fname=font_path).get_name()
matplotlib.rc('font', family=font) #폰트 설정 변경
# plt.rcParams['axes.unicode_minus']=False #마이너스 기호 깨질 때

from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [17]:
iris_data = load_iris()
# dictionary 타입
print(iris_data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [28]:
print(iris_data.target)         #숫자로 인코딩된 label 데이터
print(iris_data.target_names)   #label명
print(iris_data.feature_names)  #특성명
print(iris_data.data)           #input 데이터

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8

## knn 분류 모델로 훈련/평가 해보기

1. 데이터 전처리
    - 입력-라벨 테스트 분리
    - 훈련-테스트 데이터 분리
    - 정규화
2. 훈련
3. 평가

In [ ]:
# 입력-라벨 테스트 분리
data_df = pd.DataFrame(iris_data['data'])
target_df = pd.DataFrame(iris_data['target'])
#dictionary 타입이므로 각 key값을 저장

iris_input = data_df.to_numpy()
iris_label = target_df[0].to_numpy()

#또는

iris_df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris_df['label'] = iris_data.target
# 먼저 df에 input과 label을 모두 저장.

In [90]:
# 훈련-테스트 데이터 분리
train_input, test_input, train_label, test_label = train_test_split(
    iris_input, iris_label, test_size=0.25, random_state=42)

In [91]:
# 정규화
std_scaler = StandardScaler()

std_scaler.fit(train_input)
train_scaled = std_scaler.transform(train_input)
test_scaled = std_scaler.transform(test_input)

In [92]:
# 훈련
kn = KNeighborsClassifier()

kn.fit(train_scaled, train_label)

KNeighborsClassifier()

In [ ]:
# 평가
kn.score(test_scaled, test_label)
# 100점 나옴

1.0

In [ ]:
# 평가 지표 accuracy_score (평가 지표)
from sklearn.metrics import accuracy_score

pred = kn.predict(test_scaled)
# 에측한 값을 pred에 저장함

print(accuracy_score(test_label, pred))
# 실제 정답과 예측한 값을 인자로 넘김
# 1.0 = 100점 나옴. 정확도가 100이란 뜻
# .score()를 하면 내부적으로 accuracy_score()를 실행해 나오는 정확도 갖고 평가함

# --> 분류 task에서는 >정확도<로 평가한다!

1.0
