## Numpy: basis 실습

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. *크기가 2x2인 정규 분포로 구성된 배열*

In [2]:
import numpy as np
import random

In [ ]:

arr1 = np.zeros((4, 3))
arr2 = np.ones((3, 3))
arr3 = np.arange(0, 21, 5)
arr4 = np.linspace(0, 1, 4)
arr5 = np.random.randn(2,2)
arr6 = np.random.normal(loc=5, scale=10, size=(2, 2))

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0  5 10 15 20]
[0.         0.33333333 0.66666667 1.        ]
[[-0.74846688  0.60617425]
 [-0.08418266  0.64083887]]
[[  8.14754223   6.21519127]
 [  7.66495532 -16.06621421]]


---

In [ ]:
# NumPy basic 실습
#실습

#1
print(np.zeros((4, 3)))
#2
print(np.ones((3, 3)))
#3
print(np.arange(0, 21, 5))
#4
print(np.linspace(0, 1, 4))
#5
print(np.random.randn(2, 2))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0  5 10 15 20]
[0.         0.33333333 0.66666667 1.        ]
[[ 0.29661005 -1.57842944]
 [-0.27193189 -0.0661957 ]]


In [15]:
#실습1

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

#1
print(arr[1, 2])
#2
print(arr[:, 0])
#3
print(arr[1:3, :2])

60
[10 40 70]
[[40 50]
 [70 80]]


In [5]:
#실습2

arr = np.array([10, 20, 30, 40, 50, 60, 70])

#1
print(arr[[0, 2, 4]])
print(arr[arr>50])

[10 30 50]
[60 70]


In [ ]:
#실습3

sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

#1
print(sales[sales >= 200])


#2
list1 = []
for tf in sales[:, 2:3]<=100:
    list1.append(bool(tf))
# 각 열의 T, F 저장
print(sales[list1][:, 0:2])
#or
print(sales[sales[:, 2]<=100][:, 0:2])

#3
list2 = []
for tf in sales[:, 1:2]>=150:
    list2.append(bool(tf))
print(sales[list2])
#or
print(sales[sales[:, 1]>=150])

[200 220 300 320 310]
[[120 150]
 [ 50  45]]
[[120 150]
 [ 50  45]]
[[120 150 100]
 [200 180 220]
 [300 320 310]]
[[120 150 100]
 [200 180 220]
 [300 320 310]]


---

In [ ]:
#numpy 연산 실습

In [11]:
#실습

sales_1 = np.array([200, 340, 150, 400])
sales_2 = np.array([220, 300, 180, 420])

sales = np.add(sales_1, sales_2)
print(sales)
print(np.divide(sales, 2))

[420 640 330 820]
[210. 320. 165. 410.]


In [12]:
#실습1
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [25]:
#실습2
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1@arr2)

32


In [26]:
#실습3
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

print(arr2d+arr1d)

[[11 22 33]
 [14 25 36]]


---

In [ ]:
# Numpy 통계 실습

In [ ]:
# 실습 1 중심 경향 및 산포 측도 계산
arr = np.array([10, 20, 30, 30, 40, 50, 60])

print("평균: ", arr.mean())
print("중앙값: ", np.median(arr))

values, count = np.unique(arr, return_counts=True)
print("최빈값: ", values[count == max(count)])
print(arr.var())
print(arr.std())
print(arr.max()-arr.min())


평균:  34.285714285714285
중앙값:  30.0
최빈값:  [30]
253.06122448979593
15.90789817951435
50


In [18]:
# 실습 2 정규분포와 균등분포의 난수 생성

arr1 = np.random.randn(1000)
arr2 = np.linspace(0, 1, 1000)

print(arr1.mean(), arr1.std())
print(arr2.mean(), arr2.std())

-0.013014314346775916 0.9801951009139043
0.5 0.2889639542114209


In [24]:
# 실습3 평균 성적 구하기

# 학생별 과목 성적 데이터
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

scores_math=np.array(scores_math)
scores_english=np.array(scores_english)
scores_science=np.array(scores_science)

means=[]
for i in range(len(scores_english)):
    mean = (scores_math[i]+scores_english[i]+scores_science[i])/3
    means.append(mean)

means=np.array(means)

print(means.var(), means.std())

11.89333333333335 3.4486712417006857


---

In [29]:
# Numpy 정렬 실습

#실습1 1차원 배열 정렬

arr = np.array([50, 10, 30, 40, 20])

print('오름차순 정렬:', np.sort(arr))
print('내림차순 정렬:', np.sort(arr)[::-1])

오름차순 정렬: [10 20 30 40 50]
내림차순 정렬: [50 40 30 20 10]


In [33]:
# 실습2 2차원 배열 축 기준 정렬

arr2d = np.array([[8, 3, 5], [2, 9, 1]])

print('헹 기준 정렬:', np.sort(arr2d))
print('열 기준 정렬:', np.sort(arr2d, axis=0))

헹 기준 정렬: [[3 5 8]
 [1 2 9]]
열 기준 정렬: [[2 3 1]
 [8 9 5]]


In [35]:
# 실습3 인덱스를 반환하는 정렬

arr = np.array([15, 10, 20])

arr_index = np.argsort(arr)

arr[arr_index]

array([10, 15, 20])

---

In [ ]:
# Numpy 병합 실습

# 실습1 1차원 배열 병합

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.concatenate((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [44]:
# 실습2 2차원 배열 병합

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(np.concatenate((arr1, arr2)))
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
